### ISSUE TITLE
Fatal error: Uncaught TypeError: strpos() expects parameter 1 to be string

### ISSUE THREAD

**Issue by csheppard** [voku/simple_html_dom#32]
#### What is this feature about (expected vs actual behaviour)?
I'm working on a scraper but my script cannot recover from a fatal error if theres a problem parsing a page.

#### How can I reproduce it?
```$html = HtmlDomParser::file_get_html('https://www.lenskart.com/');```

```Fatal error: Uncaught TypeError: strpos() expects parameter 1 to be string, null given in /app/vendor/voku/simple_html_dom/src/voku/helper/HtmlDomParser.php:247
Stack trace:
#0 /app/vendor/voku/simple_html_dom/src/voku/helper/HtmlDomParser.php(247): strpos(NULL, 'type="text/html...')
#1 /app/vendor/voku/simple_html_dom/src/voku/helper/HtmlDomParser.php(614): voku\helper\HtmlDomParser->createDOMDocument(NULL, NULL)
#2 /app/vendor/voku/simple_html_dom/src/voku/helper/HtmlDomParser.php(654): voku\helper\HtmlDomParser->loadHtml('<!doctype html>...', NULL)
#3 /app/vendor/voku/simple_html_dom/src/voku/helper/HtmlDomParser.php(154): voku\helper\HtmlDomParser->loadHtmlFile('https://www.len...', NULL)
#4 /app/cli/scam-safe-checker.php(91): voku\helper\HtmlDomParser::__callStatic('file_get_html', Array)
#5 {main}
  thrown in /app/vendor/voku/simple_html_dom/src/voku/helper/HtmlDomParser.php on line 247
```

#### Any additional information?
I'm not sure what the problem with this particular website is.

**Comment by voku** [comment]
Hi and sorry for the late answer. I only fixed the issue itself (without a new test-case), because I also don't know which exactly part of the website is the reason for the issue.

fixed in version 4.6.1
